### ISSUE TITLE
'issueベースの開発'レビュー依頼

### ISSUE THREAD

**Issue by itsuki9029** [itsuki9029/-Habit-Tracker-#19]
■Webアプリの概要
ハビトラ ~Habit Tracker~は忙しい社会人が日々の習慣を管理し、フォロワーと共にモチベーションを維持しつつ
目標達成を目指すことができる習慣管理アプリです。
気になって買った本が読む習慣がない事で本棚に眠っていたり、運動不足でジョギングを始めてみても三日坊主になってしまうことは誰もが経験したことがあると思います。
本サービスではシンプルで使いやすいをコンセプトにそのような習慣化したいことを確実に習慣にできるようサポートします。
具体的には、ユーザーが設定した時間に通知が来るようにしたり、フォロワー同士で励ましあえるようコメントができます。
これらの機能を使い習慣化することで健康増進や効率的に時間を使えるなどのメリットもあります。

■1週間辺りの開発に向けられる時間
- 1週間あたり：16時間

■ProjectsのURL
https://github.com/users/itsuki9029/projects/3/views/1

■MVPリリースまで
- [x] rails new
- [x] デプロイ
- [x] トップページ
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] 習慣作成機能
- [x] チェックボックス
- [x] プロフィール編集機能
- [x] コメント機能
- [x] ユーザー検索機能
- [x] フォロー機能

■MVP後
- [x] 通知設定機能
- [x] 利用規約
- [x] プライバシーポリシー
- [x] お問い合わせ
- [x] パスワードリセット機能
- [x] パスワード更新

■MVPレビュー依頼予定日
予定日：2024年 12月 1日

**Comment by rdhdchloe** [comment]
概ね良いかと思います。LGTMです。
